# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - feature/frodriguez/changes
      - release
      - develop
      - hotfix/versionamiento
      
    
  pull_request:
    branches:
      - main
      - feature/frodriguez/changes
      - release
      - develop
      - hotfix/versionamiento
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: GitHub Tag
        if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          default_bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false 
          release_branches: develop,release,main
          
      - name: GitHub Tag others
        if: github.ref == 'refs/heads/hotfix/versionamiento'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          release_branches: hotfix/versionamiento
          
      - name: GitHub Tag others
        if: github.ref == 'refs/heads/feature/frodriguez/changes' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          default_bump: minor
          release_branches: develop,release,main
    
    
            
            
